version: '3.1'
services:
  mysqldb:
    image: mysql:latest
    container_name: adcoin
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adcoin
      MYSQL_PASSWORD: rootpass